### ISSUE TITLE
Referencing`plugin_api.dart` in flutter_map v6, incorrect `mapController` type inference

### ISSUE THREAD

**Issue by znromonk** [TesteurManiak/flutter_map_animations#10]
I get the following error when building when using
```
  flutter_map: ^6.0.0
  flutter_map_animations: ^0.5.0-dev.1
```

**Console Output**
```console
../../../.pub-cache/hosted/pub.dev/flutter_map_animations-0.5.0-dev.1/lib/src/animated_map_controller.dart:4:8:
Error: Error when reading '../../../.pub-cache/hosted/pub.dev/flutter_map-6.0.0/lib/plugin_api.dart': No such file
or directory
```

I figured this might be due to Plugin API removed in FlutterMap v6: https://docs.fleaflet.dev/v/v6/getting-started/migrating-to-v6#plugin-api-import-has-been-removed

---

Additionally, `AnimatedMapController`'s `mapController` property's type is exposed as `InvalidType`. As such, reading the values such as `_animatedMapController.mapController.bounds` cannot be compared to null since it returns an `InvalidType` data type.

**Comment by TesteurManiak** [comment]
Yes the package hasn't been migrated yet to the latest version of flutter_map, I'm on it!

**Comment by znromonk** [comment]
Wow! Thank you. This is the quickest I have seen a response+PR+and resolution done. Kudos to you @TesteurManiak
