### ISSUE TITLE
Android build conflicts

### ISSUE THREAD

**Issue by Yangyang-X** [TesteurManiak/flutter_map_animations#23]
<img width="1194" alt="Screenshot 2023-10-24 at 9 53 38 PM" src="https://github.com/TesteurManiak/flutter_map_animations/assets/26767550/dc1d2cab-5db2-400e-9ddd-722c3e5cf2d8">

This issue is also reported in package static analysis

![Screenshot 2023-10-24 at 9 57 52 PM](https://github.com/TesteurManiak/flutter_map_animations/assets/26767550/36e4bfc2-bcb7-4fde-aba9-6d7b2c9904cc)

**Comment by TesteurManiak** [comment]
I think this is due to the latest flutter_map release, I'll take a look at it.
