### ISSUE TITLE
animated marker questions

### ISSUE THREAD

**Issue by thorizer** [TesteurManiak/flutter_map_animations#25]
is the animation happening when the marker appears or disappears from the map ? does it happen when a marker moves?

**Comment by TesteurManiak** [comment]
The animation is triggered when the marker appears.
Here's the lines responsible for starting it: https://github.com/TesteurManiak/flutter_map_animations/blob/main/lib/src/animated_marker_layer.dart#L94-L97

**Comment by thorizer** [comment]
@TesteurManiak my markers move in Realtime, so they need to be recreated frequently, will that trigger the animation everytime ?

**Comment by TesteurManiak** [comment]
Yes it might considering that usually markers are not rendered when too far from the current viewport.
But you should try the example project and experiment by yourself to be sure.

**Comment by thorizer** [comment]
ok, i will try it and see how it works for my case, but there is no option to disable the marker animation? cause i need the other features

**Comment by TesteurManiak** [comment]
Technically the package is not doing marker animation by itself, it provides an `Animation<double>` in the builder callback but you're free to use it or not.
