### ISSUE TITLE
Animation `Duration` for `animateTo`

### ISSUE THREAD

**Issue by lukart03** [TesteurManiak/flutter_map_animations#35]
I would really like it if for each call to `animateTo` it was possible to set its own `duration`, which by default will be equal to the one specified in the `AnimatedMapController`, do you plan to implement this?

**Comment by TesteurManiak** [comment]
Hi the feature has been merged and is available on the main branch, will waiting for a new version on pub.dev you can point to this commit reference!: `acdcf6bc9483a16193e0996238f637806c5625cd`

**Comment by lukart03** [comment]
Hi
I didn’t expect it to be so fast) Thank you!
