### ISSUE TITLE
Flutter Hooks Support

### ISSUE THREAD

**Issue by DanPKR** [TesteurManiak/flutter_map_animations#37]
I have tried to implement AnimatedMapController using flutter hooks but an exception is thrown everytime my widget state is refreshed

`A SingleTickerProviderStateMixin can only be used as a TickerProvider once`

I think its because the AnimatedMapController internal management of the tickerprovider is reusing a single ticker instance  for different animations.

`  final mapState = useState(false);
    final ticker = useSingleTickerProvider();
    final controller = useMapController(ticker);
    final updatesStream = useStream(locationUpdates);

    if (!updatesStream.hasData) {
      return const Center(
        child: CircularProgressIndicator(),
      );
    }
    if (mapState.value) {
      controller.centerOnPoint(
          LatLng(updatesStream.data!.latitude, updatesStream.data!.longitude));
    }
    return FlutterMap(
        mapController: controller.mapController,
        options: MapOptions(
          initialCenter: LatLng(
              updatesStream.data!.latitude, updatesStream.data!.longitude),
          onMapReady: () {
            mapState.value = true;
          },`

**Comment by TesteurManiak** [comment]
Yes the controller is creating AnimationControllers dynamically, reusing the same ticker instance. You should use a TickerProviderStateMixin instead. This is what is used in the example project.
