### ISSUE TITLE
Cannot use mapController.move while using animatedRotate

### ISSUE THREAD

**Issue by MaxiStefan** [TesteurManiak/flutter_map_animations#4]
Hi @TesteurManiak,

I was testing the  animated rotation based on internal sensor bearing in flutter_map and I discovered that one cannot really zoom in when using the animatedRotate method. Do you know if there is anything that can be done about this? My animation duration is ~350ms and I believe the internal sensor sends data every ~370ms.

I was thinking to maybe not rotate if the change is < 10 degrees, which may give the other action time to take effect. This may be quite janky though.

Thanks :)

**Comment by TesteurManiak** [comment]
Is there any reason why you're not using the method `animateTo` to update the zoom and rotation simultaneously?

**Comment by MaxiStefan** [comment]
Hi @TesteurManiak,

Sorry for the delay, I've been away for work. The animation is triggered automatically as the user moves the device around and the zoom change occurs on button press. Therefore, I cannot see a way I can make this work simultaneously. Do you have any ideas?

**Comment by TesteurManiak** [comment]
I see, as of now the package allows only 1 animation at a time so I don't think you'll be able to implement this behavior with it for now. It would be needed to have a cancel mechanism for ongoing animation.

**Comment by MaxiStefan** [comment]
It is fine, for now I made it so that the animation is not triggered unless the bearing change is not greater than 10 deg. Thanks :)
