### ISSUE TITLE
Dispose a map while more than one animateTo is running causes a ticker error

### ISSUE THREAD

**Issue by JustinMyers** [TesteurManiak/flutter_map_animations#43]
The dispose method on AnimatedMapController has the following:

`final isAnimating = _animationController?.isAnimating ?? false;`

But _animationController is just the most recent animationController.

But if I've triggered two animations in quick succession, and then dispose of the map widget, the previous animation is still running and its ticker from TickerProviderStateMixin is not disposed and it breaks like the following from TickerProvider:

```  @override
  void dispose() {
    assert(() {
      if (_tickers != null) {
        for (final Ticker ticker in _tickers!) {
          if (ticker.isActive) {
            throw FlutterError.fromParts(<DiagnosticsNode>[
              ErrorSummary('$this was disposed with an active Ticker.'),
              ErrorDescription(
                '$runtimeType created a Ticker via its TickerProviderStateMixin, but at the time '
                'dispose() was called on the mixin, that Ticker was still active. All Tickers must '
                'be disposed before calling super.dispose().',
              ),
              ErrorHint(
                'Tickers used by AnimationControllers '
                'should be disposed by calling dispose() on the AnimationController itself. '
                'Otherwise, the ticker will leak.',
              ),
              ticker.describeForError('The offending ticker was'),
            ]);
          }
        }
      }
```

Is there a way to cancel AnimatedMapController animations before starting the next one? Is there a better guard against disposing it while more than one animation is running?

Also, I noticed that if one animateTo has a long duration, and you trigger a shorter one, then the fast one will zoom, complete, and then the slower one will take over the map.

Thank you for this library. Apologies if I have done a bad job at describing this issue.

**Comment by JustinMyers** [comment]
#44

**Comment by TesteurManiak** [comment]
@JustinMyers Can you please check #45 to confirm that it fixes the ticker error you are encountering.

**Comment by JustinMyers** [comment]
@TesteurManiak Hello. #45 does resolve the issue! Thank you.

While we're working in this area of the code I'm wondering if this can also help with the second part of my issue concerning animateTo calls with overlapping durations.

If I animateTo a location with a duration of 10 seconds, and then start animating to a location with a duration of 1 second, the second animation takes over, completes, and then the map resumes moving to the original destination and settles there.

My use case is roughly "I want to slowly pan to my destination so I can visualize my walk, but sometimes I want to cancel that slow pan and go back to my start location quickly."

Could we abstract the animation cancelation functionality and expose a way to call it from the AnimatedMapController?

**Comment by TesteurManiak** [comment]
>My use case is roughly "I want to slowly pan to my destination so I can visualize my walk, but sometimes I want to cancel that slow pan and go back to my start location quickly."

Would adding a parameter `cancelPreviousAnimations` to the different methods with a default global value that could be set in the constructor:
```dart
AnimatedMapController(
  // ...
  cancelPreviousAnimations: true, // Would default to false.
);
```

**Comment by JustinMyers** [comment]
Yes, I think that would work for the case where I want a fast animation to interrupt an earlier slow one.

Would this give the ability to stop an animation without issuing a new one? In that case would I just call animateTo with no parameters? That should make it cancelPreviousAnimations and just stop where it is, yes?
