### ISSUE TITLE
Topics

### ISSUE THREAD

**Issue by szakarias** [TesteurManiak/flutter_map_animations#8]
Thanks for adding topics to your package!

Due to a bug, we were not validating the names on package upload. This has been fixed and will be enforced when publishing new versions.

The guidelines for choosing topic names is https://dart.dev/tools/pub/pubspec#topics. Concretely we do not allow underscores.

Could you please update your topics names in the pubspec?

Thanks in advance and sorry for the inconvenience.

**Comment by TesteurManiak** [comment]
Sure I'll fix that right away!

**Comment by TesteurManiak** [comment]
Fixed in [v0.4.1](https://pub.dev/packages/flutter_map_animations/versions/0.4.1)
